### PR TITLE
Fix contour scaling

### PR DESCRIPTION
**Pull request by maartenbreddels**
# Pull Request Template

## Description

Fixes the resize issue described in https://github.com/spacetelescope/jdaviz/pull/199 where the contours had the same pixel coordinates even when the figure was resized or scales changed.

### CODE REVIEW

**Comment by javerbukh** [comment]
Running the following code gave me the cubeviz application layout but with nothing in the viewers. Even trying to access the viewers by reference returned an error.
```
from jdaviz import CubeViz
viz = CubeViz()
viz.app
viz.app.load_data("/Documents/manga-7495-12704-LOGCUBE_fixed.fits")
```

Screen Shot 2020-08-14 at 11 46 28 AM

**Comment by maartenbreddels** [comment]
@rosteen maybe you can take a look, maybe the js install didn't go right. Any output from the js dev console would help as well.

**Comment by rosteen** [comment]
This is working for me - I installed this, and @javerbukh's `jdaviz` PR with the contour plots, and the contours scaled properly when zooming the image as well as tracking the image when panning.

**Comment by javerbukh** [comment]
Ok, @rosteen helped get this working on my end!

I needed to do the following commands after forking and doing `pip install -e .` for this branch:
```
jupyter nbextension install --py --symlink --sys-prefix bqplot_image_gl

jupyter nbextension enable --py --sys-prefix bqplot_image_gl
```

Once I did that, it worked. @maartenbreddels this PR is good to merge from my testing.

**Comment by javerbukh** [comment]
Is this PR waiting on anything else @maartenbreddels ?

**Comment by maartenbreddels** [comment]
Thanks for the feedback!

**Pull request merged**
