### PR TITLE
feat: keydown/keyup event support

### PR DESCRIPTION
**Pull request by maartenbreddels**
this gives us keydown and keyup event support, similar to ipyevents we grab focus when the mouse moves into the div element of the Figure. Note that we also send the last mouse coordinates with the key events.

### CODE REVIEW

**Comment by pllim** [comment]
So, just to be clear, this is only enables the up/down key? Any plans to let dev define arbitrary key in the future? Just wondering.

**Comment by pllim** [comment]
Key combo (Emacs style) could also be useful but might be naturally solved by arbitrary binding?

**Comment by maartenbreddels** [comment]
There is nothing more than up/down AFAIK, there used to be a 'keypress' event but that is deprecated. Key combinations should be implemented on the Python side.

**Comment by pllim** [comment]
By Python side, do you mean in `glue-jupyter`?

**Review by astrofrog — APPROVED** [review]
Looks great, thanks! Feel free to merge and release :)

**Comment by maartenbreddels** [comment]
> By Python side, do you mean in `glue-jupyter`?

Yes, or any other Python program that uses bqplot-image-gl. Does that make sense?

**Comment by pllim** [comment]
Yes, @astrofrog has clarified for me. Thanks!

**Pull request merged**
