### PR TITLE
fix: use transparency and blend equation to get closer to original Lines

### PR DESCRIPTION
**Pull request by maartenbreddels**
This will blend the line color with the background color/line.
cc @kecnry

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@astrofrog it seems Py36 on CI it failing, I'm not sure how this CI setup works, maybe you've seen this before?

**Comment by astrofrog** [comment]
@maartenbreddels - let's just drop Python 3.6? glue-jupyter requires >=3.7

**Comment by maartenbreddels** [comment]
I agree

(from mobile phone)

Op di 19 apr. 2022 18:29 schreef Thomas Robitaille ***@***.***

**Comment by dhomeier** [comment]
GH Actions still offer 3.6 on Windows, but in #89 that's then failing on a UTF-8 read.
I left the linux-py36 there for the moment as ipywidgets and bqplot in principle still support 3.6, but have a look over there which envs should be kept in the end @maartenbreddels.

**Comment by maartenbreddels** [comment]
As said in #89, this is already an improvement, thanks Derek!

**Pull request merged**
