### PR TITLE
feat: resize & focus tracking in view_data

### PR DESCRIPTION
**Pull request by iisakkirotko**
# Pull Request Template

## Description

Stores timestamps `resized_at` and `focused_at` in `view_data`. This is useful to track which viewer figures should have their shape set based on.

@maartenbreddels and others I welcome discussion / feedback on the focus portion in particular:
- Should we also track the last point at which focus entered a view?
- Is there any need to remove the eventListener from window?

### CODE REVIEW

**Review by maartenbreddels — COMMENTED** [review]
Nice PR!
The only worry I have is that a particular view could also have received the focus event. We could also implement this later on, so we don't just listen to the window focus event, but also the element's focus event.
What do you think?

**Comment by maartenbreddels** [comment]
That is an implementation detail (or particular use case) of glue-jupyter, this is a general widget.

**Comment by iisakkirotko** [comment]
So I think I managed to track down the issue, which was in a different place than I thought. Looks like the tox scripts that are used to run tests ([OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1](https://github.com/OpenAstronomy/github-actions-workflows/blob/v1/.github/workflows/tox.yml)) seem to be using conda for installing dependencies. However, the conda-forge package for `typing_extensions` is maintained by a third party (see [this comment](https://github.com/python/typing_extensions/issues/282#issuecomment-2542325044)), and _claims_ to support Python 3.7 even in current versions, while actually support for Python 3.7 was dropped in [4.8.0](https://github.com/python/typing_extensions/releases/tag/4.8.0). This causes conda to resolve an actually incompatible version of the package, which in turn causes the tests to fail.

**Comment by maartenbreddels** [comment]
Thanks, also a nice split in commits

**Pull request merged**
